#!/usr/bin/env python
"""
Design-token generator — the heart of the F1 Analytics design system.

Reads the single source of truth (design/tokens.yml) and regenerates every
downstream artifact so the same palette / type scale drives all three surfaces:

    design/tokens.yml                 (edit this)
            |
            v   python design/build_tokens.py
    design/generated/
        _tokens.scss   -> Quarto website   (imported by styles.scss)
        tokens.py      -> Python charts     (imported by utils/f1_helpers.py)
        f1.mplstyle    -> matplotlib theme  (applied in utils setup())
        theme.json     -> Power BI theme    (also copied into serve/powerbi/)

Run it any time you change a colour or font — it is idempotent. The generated
files carry a "DO NOT EDIT" banner; tokens.yml is the only thing you hand-edit.
"""
from __future__ import annotations

import json
import shutil
from pathlib import Path

import yaml

HERE = Path(__file__).resolve().parent
ROOT = HERE.parent
TOKENS = HERE / "tokens.yml"
OUT = HERE / "generated"

BANNER = "AUTO-GENERATED by design/build_tokens.py — DO NOT EDIT. Edit design/tokens.yml."


# ---------------------------------------------------------------------------
# Load
# ---------------------------------------------------------------------------

def load_tokens() -> dict:
    with TOKENS.open(encoding="utf-8") as fh:
        return yaml.safe_load(fh)


def flatten(prefix: str, node: dict, sep: str = "-") -> dict[str, str]:
    """color.brand.teal -> {'brand-teal': '#009382', ...} (scalars only)."""
    out: dict[str, str] = {}
    for key, val in node.items():
        name = f"{prefix}{sep}{key}" if prefix else key
        if isinstance(val, dict):
            out.update(flatten(name, val, sep))
        else:
            out[name] = val
    return out


# ---------------------------------------------------------------------------
# 1. SCSS  (Quarto)
# ---------------------------------------------------------------------------

def build_scss(tok: dict) -> str:
    groups = {k: v for k, v in tok["color"].items() if k != "data"}
    colors = flatten("", groups)
    lines = [f"// {BANNER}", "", "// --- Palette --------------------------------------------------------------"]
    for name, hexval in colors.items():
        lines.append(f"$f1-{name}: {hexval};")

    data = tok["color"].get("data", [])
    if data:
        lines += [
            "",
            "// --- Categorical data palette --------------------------------------------",
            f"$f1-data: ({', '.join(data)});",
        ]

    lines += [
        "",
        "// --- Type -----------------------------------------------------------------",
        f"$f1-font-family: {tok['typography']['family']};",
        f"$f1-radius-sm: {tok['radius']['sm']};",
        "",
        "// --- Bootstrap / Quarto theme overrides (consumed in the defaults layer) --",
        "$primary:    $f1-brand-teal;",
        "$body-bg:    $f1-surface-base;",
        "$body-color: $f1-text-primary;",
        "$link-color: $f1-brand-teal_bright;",
        "",
    ]
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# 2. Python  (matplotlib / utils)
# ---------------------------------------------------------------------------

def _const(name: str) -> str:
    return name.upper().replace("-", "_")


def build_python(tok: dict) -> str:
    c = tok["color"]
    ty = tok["typography"]
    ch = tok["chart"]

    def group(node: dict, prefix: str = "") -> list[str]:
        out = []
        for k, v in node.items():
            out.append(f'{_const(prefix + k)} = "{v}"')
        return out

    lines = [
        f'"""{BANNER}"""',
        "from pathlib import Path",
        "",
        "# --- Brand ---------------------------------------------------------------",
        *group(c["brand"], "brand_"),
        "",
        "# --- Surfaces ------------------------------------------------------------",
        *group(c["surface"], "surface_"),
        "",
        "# --- Text ----------------------------------------------------------------",
        *group(c["text"], "text_"),
        "",
        "# --- Axis furniture ------------------------------------------------------",
        *group(c["axis"], "axis_"),
        "",
        "# --- Semantic ------------------------------------------------------------",
        *group(c["semantic"], "semantic_"),
        "",
        "# --- Grouped lookups -----------------------------------------------------",
        "COMPOUND_COLORS = {",
        *[f'    "{k.upper()}": "{v}",' for k, v in c["compound"].items()],
        "}",
        "",
        "SEMANTIC = {",
        *[f'    "{k}": "{v}",' for k, v in c["semantic"].items()],
        "}",
        "",
        "# --- Categorical palette (matplotlib colour cycle, multi-series) ---------",
        "DATA_COLORS = [",
        *[f'    "{v}",' for v in c.get("data", [])],
        "]",
        "",
        "# --- Type scale (pt) -----------------------------------------------------",
        "FONT_FAMILY = " + json.dumps(ty["family"]),
        *[f"FONT_{k.upper()} = {v}" for k, v in ty["size"].items()],
        "",
        "# --- Chart defaults ------------------------------------------------------",
        f"FIG_DPI = {ch['fig_dpi']}",
        f"LINE_WIDTH = {ch['line_width']}",
        f"GRID_ALPHA = {ch['grid_alpha']}",
        "",
        "# Absolute path to the matplotlib stylesheet (apply via plt.style.use).",
        'MPLSTYLE = str(Path(__file__).with_name("f1.mplstyle"))',
        "",
    ]
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# 3. matplotlib stylesheet
# ---------------------------------------------------------------------------

def _bare(hexval: str) -> str:
    """matplotlib rc files want hex without the leading '#'."""
    return hexval.lstrip("#")


def build_mplstyle(tok: dict) -> str:
    c = tok["color"]
    ty = tok["typography"]
    ch = tok["chart"]
    rows = [
        f"# {BANNER}",
        "",
        f"figure.facecolor:  {_bare(c['surface']['base'])}",
        f"savefig.facecolor: {_bare(c['surface']['base'])}",
        f"savefig.dpi:       {ch['fig_dpi']}",
        f"axes.facecolor:    {_bare(c['surface']['base'])}",
        f"axes.edgecolor:    {_bare(c['axis']['spine'])}",
        f"axes.labelcolor:   {_bare(c['text']['on_chart'])}",
        f"axes.titlecolor:   {_bare(c['text']['on_chart'])}",
        "axes.titleweight:  bold",
        "axes.spines.top:   False",
        "axes.spines.right: False",
        f"text.color:        {_bare(c['text']['on_chart'])}",
        f"xtick.color:       {_bare(c['text']['on_chart'])}",
        f"ytick.color:       {_bare(c['text']['on_chart'])}",
        f"grid.color:        {_bare(c['axis']['grid'])}",
        f"grid.alpha:        {ch['grid_alpha']}",
        "axes.grid:         False",
        f"lines.linewidth:   {ch['line_width']}",
        f"legend.facecolor:  {_bare(c['surface']['raised'])}",
        f"legend.edgecolor:  {_bare(c['surface']['raised'])}",
        "legend.labelcolor: white",
        "font.family:       sans-serif",
        f"axes.titlesize:    {ty['size']['title']}",
        f"axes.labelsize:    {ty['size']['axis_label']}",
        f"xtick.labelsize:   {ty['size']['tick']}",
        f"ytick.labelsize:   {ty['size']['tick']}",
        f"legend.fontsize:   {ty['size']['legend']}",
    ]
    data = c.get("data", [])
    if data:
        cyc = ", ".join(f"'{_bare(h)}'" for h in data)
        rows.append(f"axes.prop_cycle: cycler('color', [{cyc}])")
    rows.append("")
    return "\n".join(rows)


# ---------------------------------------------------------------------------
# 4. Power BI theme
# ---------------------------------------------------------------------------

def build_powerbi(tok: dict) -> dict:
    c = tok["color"]
    ty = tok["typography"]
    family = ty["family"].split(",")[0].strip().strip("'\"")

    # Categorical palette — the brand data ramp (falls back to a built set).
    data_colors = c.get("data") or [
        c["brand"]["teal"], c["compound"]["medium"], c["semantic"]["positive"],
        c["compound"]["wet"], c["text"]["muted"], c["compound"]["hard"],
        c["brand"]["teal_bright"], c["surface"]["raised"],
    ]

    def solid(color: str) -> list[dict]:
        return [{"color": {"solid": {"color": color}}}]

    def label(size: int) -> list[dict]:
        return [{"fontColor": {"solid": {"color": c["text"]["primary"]}},
                 "fontFamily": family, "fontSize": size}]

    return {
        "name": tok["meta"]["name"],
        "dataColors": data_colors,
        "background": c["surface"]["base"],
        "foreground": c["text"]["primary"],
        "tableAccent": c["brand"]["teal"],
        "good": c["semantic"]["positive"],
        "neutral": c["compound"]["medium"],
        "bad": c["semantic"]["negative"],
        "maximum": c["brand"]["teal"],
        "center": c["compound"]["medium"],
        "minimum": c["surface"]["base"],
        "null": c["text"]["faint"],
        "hyperlink": c["brand"]["teal_bright"],
        "visualStyles": {
            "*": {
                "*": {
                    "background": [{"color": {"solid": {"color": c["surface"]["raised"]}},
                                    "transparency": 0}],
                    "border": [{"color": {"solid": {"color": c["surface"]["border"]}},
                                "radius": 6, "show": True}],
                    "title": [{"fontColor": {"solid": {"color": c["text"]["primary"]}},
                               "background": {"solid": {"color": c["surface"]["raised"]}},
                               "fontFamily": family,
                               "fontSize": ty["size"]["subtitle"]}],
                    "labels": label(ty["size"]["legend"]),
                    "categoryAxis": [{"labelColor": {"solid": {"color": c["text"]["muted"]}},
                                      "gridlineColor": {"solid": {"color": c["axis"]["spine"]}}}],
                    "valueAxis": [{"labelColor": {"solid": {"color": c["text"]["muted"]}},
                                   "gridlineColor": {"solid": {"color": c["axis"]["spine"]}}}],
                }
            },
            "page": {"*": {"background": [{"color": {"solid": {"color": c["surface"]["base"]}},
                                           "transparency": 0}]}},
        },
    }


# ---------------------------------------------------------------------------
# Write
# ---------------------------------------------------------------------------

def write(path: Path, content: str) -> None:
    path.write_text(content, encoding="utf-8")
    print(f"  + {path.relative_to(ROOT)}")


def main() -> int:
    tok = load_tokens()
    OUT.mkdir(parents=True, exist_ok=True)
    (OUT / "__init__.py").write_text(
        f'"""{BANNER}\n\nGenerated design-token artifacts. Edit design/tokens.yml instead."""\n',
        encoding="utf-8",
    )

    print(f"Building design tokens from {TOKENS.relative_to(ROOT)} ...")
    write(OUT / "_tokens.scss", build_scss(tok))
    write(OUT / "tokens.py", build_python(tok))
    write(OUT / "f1.mplstyle", build_mplstyle(tok))

    theme = build_powerbi(tok)
    theme_json = json.dumps(theme, indent=2) + "\n"
    write(OUT / "theme.json", theme_json)

    # Drop a copy next to the Power BI report for easy "Browse for themes".
    pbi = ROOT / "serve" / "powerbi" / "F1Analytics.theme.json"
    if pbi.parent.exists():
        pbi.write_text(theme_json, encoding="utf-8")
        print(f"  + {pbi.relative_to(ROOT)}  (import via Power BI: View > Themes > Browse)")

    print("Done.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
